Issue 2
slub/liszt_common pull request #15
Opened 2024-03-27 13:20 UTC by Nathmel123

Implemented mei-xml conversion.

2024-03-27 14:22 UTC, dikastes requested changes
Great result, some minor formatting issues and I have some small and two big desires concerning styling.

2024-03-27 14:22 UTC, dikastes commented on Classes/Common/XmlDocument.php
> +        }
See https://laravel.com/docs/11.x/collections#method-mapwithkeys

2024-03-27 14:22 UTC, dikastes commented on Classes/Common/XmlDocument.php
> +use SimpleXMLElement;
use Illuminate\Support\Collection;

2024-03-27 14:22 UTC, dikastes commented on Classes/Common/XmlDocument.php
> +use SimpleXMLElement;
see below why

2024-03-27 14:22 UTC, dikastes commented on Classes/Common/XmlDocument.php
> +            $result['@xml:id'] = $trimmedXmlId;
indentation

2024-03-27 14:22 UTC, dikastes commented on Classes/Common/XmlDocument.php
> +
superfluous empty line

2024-04-25 09:38 UTC, Nathmel123 commented
Collection usage for children is not functional, please do not merge.

2024-05-02 09:24 UTC, Nathmel123 commented
Illuminate\Support\Collection->each() does not work properly. I replaced it with foreach, maybe there is another solution, but for the moment this is the best solution.

2024-05-02 09:26 UTC, Nathmel123 commented on Classes/Common/XmlDocument.php
> +        }
See my comment. The foreach loop is the best solution for now, Collection->each() does weird things.

2024-05-02 09:53 UTC, Nathmel123 commented
If a node is splited, its xmlId is not included, if xmlId parsing is off. It should be enabled.

2024-07-05 14:18 UTC, dikastes requested changes

2024-07-05 14:18 UTC, dikastes commented on Classes/Common/XmlDocument.php
> +        // Check if array is already converted
great idea!

2024-07-05 14:18 UTC, dikastes commented on Classes/Common/XmlDocument.php
> +        foreach ($xmlArray as $id => $value) {
? ```php $this->convertedArray``` should always consist of just one element?

2024-07-05 14:18 UTC, dikastes commented on Classes/Common/XmlDocument.php
> +        return $result;
I'd expect a JSON string, not an array

2024-07-05 14:18 UTC, dikastes commented on Tests/Unit/Common/XmlDocumentTest.php
> +
provide more tests (probably not making use of files) with minimal examples:
- convert attribute
- convert text value
- convert mixed content
- all config options

2024-09-05 08:48 UTC, Nathmel123 commented
Somehow the checks fail at my machine, if I merge dev into issue-2 and than pull

2024-09-05 09:02 UTC, Nathmel123 commented
Fixed

2024-09-09 11:33 UTC, dikastes approved these changes

2024-09-09 11:34 UTC, merged